import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  backgroundAnimation: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: -1,
  },
  header: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 50,
    zIndex: 2,
  },
  title: {
    marginTop: 120,
    color: '#153A90',
    fontSize: 22,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    letterSpacing: 0.5,
  },
  logo: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
    marginBottom: 20,
    transform: [{ scale: 1 }],
  },
  logoAnimation: {
    transform: [{ scale: 1.05 }],
  },
  formContainer: {
    flex: 2,
    margin: 25,
    padding: 30,
    borderRadius: 20,
    width: '90%',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backdropFilter: 'blur(10px)',
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  formTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 48,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  icon: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    transform: [{ rotate: '0deg' }],
  },
  iconAnimation: {
    transform: [{ rotate: '10deg' }],
  },
  inputContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  inputLabel: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 8,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  input: {
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 255, 255, 0.8)',
    outlineWidth: 0,
    fontWeight: '500',
    height: 50,
    marginBottom: 25,
    color: 'white',
    fontSize: 16,
    paddingLeft: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    paddingVertical: 12,
  },
  inputFocus: {
    borderBottomColor: '#fff',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    transform: [{ translateY: -2 }],
  },
  btl: {
    backgroundColor: '#153a90',
    height: 55,
    width: '65%',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
    borderRadius: 28,
    alignSelf: 'center',
    marginTop: 30,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 10,
    elevation: 5,
    position: 'relative',
    overflow: 'hidden',
  },
  buttonGlow: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    width: 50,
    height: '100%',
    transform: [{ skewX: '-20deg' }],
    left: -50,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  rg: {
    flex: 0.3,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 30,
    marginBottom: 50,
  },
  linkText: {
    color: '#153a90',
    fontSize: 16,
    fontWeight: 'bold',
    textDecorationLine: 'none',
    marginBottom: 60,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
    position: 'relative',
  },
  linkUnderline: {
    position: 'absolute',
    bottom: -5,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#153a90',
    width: '0%',
  },
  linkUnderlineActive: {
    width: '100%',
  },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    width: '90%',
    maxWidth: 450,
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#E7701D',
    marginTop: 15,
    marginBottom: 10,
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 25,
    paddingHorizontal: 10,
  },
  modalButton: {
    backgroundColor: '#E7701D',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    width: '100%',
    maxWidth: 200,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E7701D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  modalButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  modalFooterText: {
    fontSize: 13,
    color: '#777',
    textAlign: 'center',
    marginTop: 20,
    fontStyle: 'italic',
  },
  warningIconContainer: {
    backgroundColor: 'rgba(231, 112, 29, 0.1)',
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  errorText: {
    color: '#fff',
    textAlign: 'center',
    marginBottom: 15,
    fontWeight: 'bold',
    padding: 10,
    borderRadius: 8,
    width: '100%',
    fontSize:15
  },
  // Animações para partículas
  particleContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  particle: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
  },

  resendText: {
    color: '#153a90',
    marginTop: 8,
    textDecorationLine: 'underline',
    textAlign: 'center',
    fontWeight: 'bold'
  },
  errodesgramado:{
    marginTop:10
  }
});


