import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
   container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#153A90',
        paddingTop: Platform.OS === 'ios' ? 50 : 20,
        paddingBottom: 16,
        paddingHorizontal: 20,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    pressedBack: {
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    headerContent: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#cbd5e1',
        marginTop: 2,
    },
    headerSpacer: {
        width: 40,
    },
    progressContainer: {
        backgroundColor: '#ffffff',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
    },
    progressBar: {
        height: 4,
        backgroundColor: '#e2e8f0',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#10b981',
        borderRadius: 2,
    },
    progressText: {
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center',
        marginTop: 8,
        fontWeight: '500',
    },
    scrollContainer: {
        flexGrow: 1,
        paddingBottom: 20,
    },
    formContainer: {
        flex: 1,
        paddingHorizontal: 20,
    },
    welcomeSection: {
        alignItems: 'center',
        paddingVertical: 24,
        backgroundColor: '#ffffff',
        marginTop: 16,
        borderRadius: 16,
        marginBottom: 20,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    title: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1e293b',
        textAlign: 'center',
        marginTop: 12,
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 15,
        color: '#64748b',
        textAlign: 'center',
        lineHeight: 22,
        paddingHorizontal: 16,
    },
    section: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 4,
    },
    sectionDescription: {
        fontSize: 13,
        color: '#6b7280',
        marginBottom: 20,
        lineHeight: 18,
    },
    photosGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    photoButton: {
        width: '47%',
        aspectRatio: 1,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#d1d5db',
        borderStyle: 'dashed',
        backgroundColor: '#f9fafb',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    photoButtonFilled: {
        borderStyle: 'solid',
        borderColor: '#10b981',
        backgroundColor: '#ffffff',
    },
    photoButtonPressed: {
        backgroundColor: '#f3f4f6',
        borderColor: '#9ca3af',
    },
    photoContainer: {
        width: '100%',
        height: '100%',
        position: 'relative',
    },
    photoImage: {
        width: '100%',
        height: '100%',
    },
    photoOverlay: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    addPhotoContent: {
        alignItems: 'center',
        gap: 8,
    },
    addPhotoText: {
        fontSize: 12,
        color: '#6b7280',
        fontWeight: '500',
    },
    photoCount: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 16,
        gap: 6,
    },
    photoCountText: {
        fontSize: 13,
        color: '#10b981',
        fontWeight: '500',
    },
    buttonContainer: {
        marginTop: 8,
        marginBottom: 20,
    },
    continueButton: {
        backgroundColor: '#10b981',
        borderRadius: 12,
        paddingVertical: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        elevation: 2,
        shadowColor: '#10b981',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    pressedButton: {
        backgroundColor: '#059669',
    },
    buttonDisabled: {
        backgroundColor: '#9ca3af',
        elevation: 0,
        shadowOpacity: 0,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
    helpText: {
        fontSize: 12,
        color: '#6b7280',
        textAlign: 'center',
        marginTop: 12,
        lineHeight: 16,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        gap: 12,
    },
    loadingText: {
        fontSize: 14,
        color: '#374151',
        fontWeight: '500',
    },
});
